[package]
edition = "2024"
license = "GPL-3.0"
name    = "gnosis_vpn-server"
version = "0.4.3"

[lib]
name = "gnosis_vpn_server"
path = "src/lib.rs"

[dependencies]
anyhow             = "1.0.104"
clap               = { version = "4.6.5", features = ["derive", "env"] }
figment            = "0.10.19"
prometheus         = "0.14"
rand               = "0.10.2"
rocket             = { version = "0.5.1", features = ["json"] }
serde              = { version = "1.0.229", features = ["derive"] }
serde_json         = "1.0.151"
thiserror          = "2.0.19"
tokio              = { version = "1.53.1", features = ["rt", "time"] }
toml               = "1.1.4"
tracing            = "0.1.44"
tracing-subscriber = "0.3.23"
