# Maintained by gnosis_vpn-server

# Sample interface section for WireGuard VPN server configuration
[Interface]
PrivateKey = <server private key>
Address = 10.128.0.1/32
PostUp = iptables -t nat -A POSTROUTING -s 10.128.0.0/9 -o ens3 -j MASQUERADE
PostDown = iptables -t nat -D POSTROUTING -s 10.128.0.0/9 -o ens3 -j MASQUERADE
