[Interface]
Address = 10.129.0.1/32
ListenPort = 51820
PrivateKey = <private key>
# NAT so connected clients can reach the external network via the container's eth0
PostUp = iptables -t nat -A POSTROUTING -s 10.129.0.0/24 -o eth0 -j MASQUERADE
PostUp = iptables -I FORWARD -i wggvpn -o eth0 -j ACCEPT
PostUp = iptables -I FORWARD -i eth0 -o wggvpn -m state --state RELATED,ESTABLISHED -j ACCEPT
PreDown = iptables -D FORWARD -i wggvpn -o eth0 -j ACCEPT
PreDown = iptables -D FORWARD -i eth0 -o wggvpn -m state --state RELATED,ESTABLISHED -j ACCEPT
PreDown = iptables -t nat -D POSTROUTING -s 10.129.0.0/24 -o eth0 -j MASQUERADE
