name: Build
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
concurrency:
  group: ${{ github.ref }}-build
  cancel-in-progress: true
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Use Nix Cache
        uses: cachix/cachix-action@v16
        with:
          name: gnosis-vpn-server
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        env:
          USER: runner

      - name: Setup GCP
        id: gcp
        uses: hoprnet/hopr-workflows/actions/setup-gcp@12c56020e16036982e6cc529848edeedfc705865 # master
        with:
          google-credentials: ${{ secrets.GCP_SA_GITHUB_ACTIONS }}
          login-artifact-registry: 'true'

      - name: Build
        run: nix build .#gvpn -L

      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@0543b277721e852d821c6738d449f2f4dea03d5f # v1.0.9

      - name: Prepare Docker image
        id: vars
        run: |
          set -x
          pr_version=$(grep -E '^version\s*=' Cargo.toml | awk -F\" '{print $2}')-pr.${{ github.event.pull_request.number }}
          TAGS="${{ vars.DOCKER_IMAGE_REGISTRY }}/${{ vars.DOCKER_IMAGE_NAME }}:${pr_version}"
          if [[ -n "${GITHUB_PR_LABEL_DEPLOY_DEV}" ]]; then
            TAGS="$TAGS,${{ vars.DOCKER_IMAGE_REGISTRY }}/${{ vars.DOCKER_IMAGE_NAME }}:dev"
          fi
          echo "tags=$TAGS" | tee -a "$GITHUB_OUTPUT"
          cp result/bin/gnosis_vpn-server docker/
          chmod 775 docker/gnosis_vpn-server

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          push: true
          tags: ${{ steps.vars.outputs.tags }}

      - name: Trigger restart deployment
        if: env.GITHUB_PR_LABEL_DEPLOY_DEV == '1' 
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
        with:
          token: ${{ secrets.GH_SELF_HOSTED_RUNNER_TOKEN }}
          repository: hoprnet/gitops
          event-type: restart_deployment
          client-payload: |-
            {
              "environment": "staging",
              "namespace": "gnosisvpn",
              "label_selector": "app.kubernetes.io/name=gnosisvpn-dev"
            }

  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Use Nix Cache
        uses: cachix/cachix-action@v16
        with:
          name: gnosis-vpn-client
        env:
          USER: runner
      - name: Lint and formatting check
        run: nix run .#check
  unittest:
    name: Unit test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Use Nix Cache
        uses: cachix/cachix-action@v16
        with:
          name: gnosis-vpn-client
        env:
          USER: runner
      - name: Run unit tests
        run: nix build .#gvpn-test
  systemtest:
    name: System test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Use Nix Cache
        uses: cachix/cachix-action@v16
        with:
          name: gnosis-vpn-client
          extraPullNames: "hoprnet"
          # for some reason this fails:
          # authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        env:
          USER: runner
      - name: Install reqs via apt
        run: sudo apt-get install -y just jq
      - name: Run system tests
        run: just system-setup ci-system-test
  build-binaries:
    strategy:
      matrix:
        binary:
          - architecture: x86_64-linux
            runner: ubuntu-latest
          - architecture: aarch64-linux
            runner: ubuntu-latest
          - architecture: armv7l-linux
            runner: ubuntu-latest
    name: Binary ${{ matrix.binary.architecture }}
    uses: ./.github/workflows/build-binaries.yaml
    with:
      branch: ${{ github.event.pull_request.head.ref }}
      runner: ${{ matrix.binary.runner }}
      architecture: ${{ matrix.binary.architecture }}
      version_type: "commit"
    secrets: inherit
