name: Merge PR
on:
  pull_request:
    types:
      - closed
      # - synchronize
    branches:
      - main
concurrency:
  group: merge
  cancel-in-progress: false
jobs:
  build-binaries:
    strategy:
      matrix:
        binary:
          - architecture: x86_64-linux
            runner: depot-ubuntu-22.04-4
    name: Binary ${{ matrix.binary.architecture }}
    uses: ./.github/workflows/build-binaries.yaml
    with:
      branch: ${{ github.sha }} # Use the commit SHA as the branch is deleted after the PR is merged
      runner: ${{ matrix.binary.runner }}
      architecture: ${{ matrix.binary.architecture }}
      version_type: "pr"
    secrets: inherit
  cache-deps:
    name: Cache deps
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/cache-deps.yaml
    with:
      branch: ${{ github.event.pull_request.base.ref }}
    secrets: inherit
