---
name: PR
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
concurrency:
  group: ${{ github.ref }}-build
  cancel-in-progress: true
env:
  CARGO_TERM_COLOR: always
jobs:
  build-binaries:
    name: Binary ${{ matrix.architecture }}
    if: ${{ github.event.pull_request.head.repo.fork == false }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: x86_64-linux
            runner: depot-ubuntu-22.04-4
            build_command: nix build -L .#binary-gnosis_vpn-server-x86_64-linux
            required_label: ""
          - architecture: aarch64-linux
            runner: depot-ubuntu-22.04-arm-4
            build_command: nix build -L .#binary-gnosis_vpn-server-aarch64-linux
            required_label: "binary:aarch64-linux"
    uses: hoprnet/hopr-workflows/.github/workflows/build-binaries.yaml@9d3880d21d35d3ee6d3bc5cde6b62e91a84b56d8 # build-binaries-v3
    permissions:
      contents: read
      id-token: write
    with:
      source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
      version_type: commit
      architecture: ${{ matrix.architecture }}
      cachix_cache_name: gnosis-vpn-server
      build_command: ${{ matrix.build_command }}
      binary: gnosis_vpn-server
      gcp_workload_identity_provider: projects/277369779617/locations/global/workloadIdentityPools/github-workflow-pool/providers/github-provider
      gcp_service_account: github-workflows@hoprassociation.iam.gserviceaccount.com
      runner: ${{ matrix.runner }}
      enabled: ${{ matrix.required_label == '' || contains(github.event.pull_request.labels.*.name, matrix.required_label)
        }}
    secrets:
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      gpg_private_key_password: ${{ secrets.GPG_PRIVATE_KEY_PASSWORD }}
  build-docker:
    name: Docker
    if: ${{ github.event.pull_request.head.repo.fork == false }}
    uses: hoprnet/hopr-workflows/.github/workflows/build-docker.yaml@9d3880d21d35d3ee6d3bc5cde6b62e91a84b56d8 # build-docker-v3
    needs: build-binaries
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    with:
      source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
      version_type: commit
      build_matrix: |
        [
          {
            "runner": "depot-ubuntu-22.04-4",
            "architecture": "x86_64-linux",
            "build_command": "nix run .#docker-gnosis_vpn-server-x86_64-linux"
          }
        ]
      cachix_cache_name: gnosis-vpn-server
      docker_image_name: gnosis_vpn-server
      docker_gcp_registry: europe-west3-docker.pkg.dev/gnosisvpn-production/docker-images
      docker_image_format: docker
      docker_bucket_sboms: gnosisvpn-production-docker-images-sboms
      fail_on_scan_vulnerabilities: ${{ vars.FAIL_ON_SCAN_VULNERABILITIES }}
      gcp_workload_identity_provider: projects/277369779617/locations/global/workloadIdentityPools/github-workflow-pool/providers/github-provider
      gcp_service_account: github-workflows@hoprassociation.iam.gserviceaccount.com
    secrets:
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
  checks:
    name: Checks
    if: ${{ github.event.pull_request.head.repo.fork == false }}
    runs-on: depot-ubuntu-22.04-4
    permissions:
      contents: read
    steps:
      - name: Run checks
        uses: hoprnet/hopr-workflows/actions/nix-action@9d3880d21d35d3ee6d3bc5cde6b62e91a84b56d8 # nix-action-v1
        with:
          source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
          cachix_cache_name: gnosis-vpn-server
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          command: nix flake check -L --show-trace --max-jobs 1
